'use client';
import { useEffect, useState, useCallback, useRef } from 'react';
import { Activity, ArrowUpRight, ArrowDownRight, ArrowRight, Clock3, ShieldCheck, Radio, RefreshCw, Download, Database, Layers3, Search, ExternalLink, ChevronDown, CircleHelp, BarChart3, BookOpen, LockKeyhole } from 'lucide-react';
import { ASSETS, NAMES } from '@/lib/market-data.mjs';
import MarketComparator from '@/components/market-comparator';
import DailyCalendar from '@/components/daily-calendar';
const pct=(x:any)=>x===null||x===undefined||!Number.isFinite(x)?'—':(x*100).toFixed(1)+'%';
const money=(x:any)=>x===null||x===undefined||!Number.isFinite(x)?'—':'$'+new Intl.NumberFormat('es-MX',{maximumFractionDigits:x<1?7:2,minimumFractionDigits:x<1?4:2}).format(x);
const time=(x:any)=>!x?'—':new Intl.DateTimeFormat('es-MX',{timeZone:'America/Mexico_City',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(x);
const date=(x:any)=>!x?'—':new Intl.DateTimeFormat('es-MX',{timeZone:'America/Mexico_City',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(x);
const colors:any={BTC:'#eea347',ETH:'#99aaff',SOL:'#b195f9',XRP:'#d1dae6',DOGE:'#d4b867',BNB:'#edc24b'};
const symbols:any={BTC:'₿',ETH:'Ξ',SOL:'S',XRP:'X',DOGE:'Ð',BNB:'B'};
function remaining(t:number,now:number){if(!t)return '—';const s=Math.max(0,Math.floor((t-now)/1000));return Math.floor(s/60).toString().padStart(2,'0')+':'+(s%60).toString().padStart(2,'0');}
function Chart({points,small=false}:{points:any[];small?:boolean}){const a=points?.filter(x=>Number.isFinite(x.c))??[];if(a.length<2)return <div className={'empty-chart '+(small?'small':'')}><Activity size={small?19:30}/>{!small&&<span>Esperando histórico verificado.<br/>No se utilizan curvas de demostración.</span>}</div>;const w=small?180:760,h=small?55:220,min=Math.min(...a.map(x=>x.c)),max=Math.max(...a.map(x=>x.c)),range=Math.max(max-min,min*.00005);const path=a.map((x,i)=>(i?'L':'M')+(i/(a.length-1)*w).toFixed(2)+','+(h-12-(x.c-min)/range*(h-24)).toFixed(2)).join(' '),positive=a.at(-1).c>=a[0].c;return <svg viewBox={'0 0 '+w+' '+h} className={small?'sparkline':'price-chart'} role="img" aria-label="Histórico spot, no predicción"><path d={path} fill="none" stroke={positive?'#68d6b1':'#e58e93'} strokeWidth={small?2:2.5}/>{!small&&<><path d={path+' L '+w+','+h+' L 0,'+h+' Z'} fill={positive?'#68d6b1':'#e58e93'} opacity=".06"/><line x1="0" x2={w} y1={h/2} y2={h/2} stroke="#394039" strokeDasharray="5 7"/></>}</svg>;}
function JsonButton({value,label='Exportar JSON'}:{value:()=>Promise<any>;label?:string}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <><button className="button subtle" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const v=await value();const u=URL.createObjectURL(new Blob([JSON.stringify(v,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='MONEY_OMEGA_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(u);}catch{setError('No se pudo exportar.');}finally{setBusy(false);}}}><Download size={15}/>{busy?'Preparando…':label}</button>{error&&<span className="error-text">{error}</span>}</>;}
const sources=[
  ['Kraken USD','REST PÚBLICO VERIFICADO','Histórico5m y ticker de los seis activos verificados en el servidor. Fuente del modelo spot; no es el oráculo del contrato.','https://docs.kraken.com/api-reference/market-data/get-ohlc-data'],
  ['Coinbase spot','REST PÚBLICO VERIFICADO','Ticker público observado para BTC, ETH, SOL, XRP y DOGE. BNB-USD no verificado. No hay acceso a tu cuenta.','https://docs.cdp.coinbase.com/api-reference/exchange-api/rest-api/products/get-product-ticker'],
  ['Kalshi / Coinbase Predictions','REST PÚBLICO VERIFICADO','Contratos15m de los seis activos observados. No se verificó el catálogo de tu cuenta ni costes de Coinbase. Resolución según RTI/reglas.','https://help.coinbase.com/en/coinbase/trading-and-funding/prediction-markets/intro'],
  ['Polymarket','REST PÚBLICO VERIFICADO','Gamma y libros bid/ask5/15/60m. Los contratos revisados5/15m usan Chainlink USD/TWAP60s;1h usa vela Binance USDT. Referencia exacta puede faltar.','https://docs.polymarket.com/market-data/realtime-data'],
  ['Predict.fun / Binance Wallet','CLAVE OFICIAL PENDIENTE','Adaptador de lectura Mainnet. API exige x-api-key en el servidor. Se consulta el catálogo de cada activo y ventana; no se presume oferta de SOL, XRP o DOGE.','https://dev.predict.fun/'],
  ['MetaMask','RUTA DIRECTA PENDIENTE','Proveedor Polymarket. La documentación publica4% de transacción. No se calcula un coste final de wallet sin cotización de la ruta.','https://support.metamask.io/manage-crypto/prediction-markets'],
  ['Trust Wallet','PENDIENTE','Integra Polymarket, Predict.fun e HIP-4. API requiere AccessID/HMAC. No se conectó wallet ni se afirma elegibilidad regional.','https://trustwallet.com/prediction-markets'],
  ['Binance','DETENIDO · RESTRICCIÓN GEOGRÁFICA','HTTP451 en prueba. No se reintenta ni evade. Kraken es fuente/modelo separado, no Binance ni referencia contractual.','https://developers.binance.com/en/docs/catalog/core-trading-spot-trading/api/rest-api/market']
];
export default function Home(){
  const [tab,setTab]=useState('compare'),[asset,setAsset]=useState('BTC'),[horizon,setHorizon]=useState(5),[filter,setFilter]=useState('');
  const [data,setData]=useState<Record<string,any>>({}),[quotes,setQuotes]=useState<Record<string,any>>({}),[matrix,setMatrix]=useState<any>(null),[archive,setArchive]=useState<any>(null);
  const [now,setNow]=useState(0),[busy,setBusy]=useState(false),[marketBusy,setMarketBusy]=useState(false);
  const running=useRef(false),marketRunning=useRef(false),mounted=useRef(true),abort=useRef<AbortController|null>(null);
  const refreshAnalysis=useCallback(async()=>{if(running.current)return;running.current=true;setBusy(true);abort.current=new AbortController();await Promise.all(ASSETS.map(async a=>{try{const r=await fetch('/api/analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asset:a}),signal:abort.current!.signal});if(!r.ok)throw new Error();const j:any=await r.json();if(mounted.current)setData(d=>({...d,[a]:j}));}catch(e:any){if(e.name!=='AbortError'&&mounted.current)setData(d=>({...d,[a]:{forecasts:[],candles:[],error:'Servidor no disponible'}}));}}));running.current=false;if(mounted.current)setBusy(false);},[]);
  const refreshQuotes=useCallback(async()=>{await Promise.all(ASSETS.map(async a=>{try{const r=await fetch('/api/quotes?asset='+a);if(!r.ok)throw new Error();const j:any=await r.json();if(mounted.current)setQuotes(d=>({...d,[a]:j}));}catch{if(mounted.current)setQuotes(d=>({...d,[a]:{quotes:[],error:'Consulta fallida'}}));}}));},[]);
  const refreshMarkets=useCallback(async()=>{if(marketRunning.current)return;marketRunning.current=true;setMarketBusy(true);try{const r=await fetch('/api/matrix');if(!r.ok)throw new Error();const j:any=await r.json();if(mounted.current)setMatrix(j);}catch{if(mounted.current)setMatrix({rows:[],error:'Comparador no disponible. No se presentan cuotas anteriores como actuales.'});}finally{marketRunning.current=false;if(mounted.current)setMarketBusy(false);}},[]);
  const refreshJournal=useCallback(async()=>{try{const r=await fetch('/api/history?asset=ALL&limit=100');setArchive(await r.json());}catch{setArchive({records:[],summary:[],error:'Registro no disponible'});}},[]);
  useEffect(()=>{mounted.current=true;setNow(Date.now());refreshAnalysis();refreshQuotes();let slot=Math.floor(Date.now()/300000);const tick=setInterval(()=>{const n=Date.now();setNow(n);const s=Math.floor(n/300000);if(!document.hidden&&s!==slot){slot=s;refreshAnalysis();}},1000);const prices=setInterval(()=>{if(!document.hidden)refreshQuotes();},10000);const visibility=()=>{if(!document.hidden){refreshAnalysis();refreshQuotes();}};document.addEventListener('visibilitychange',visibility);return()=>{mounted.current=false;abort.current?.abort();clearInterval(tick);clearInterval(prices);document.removeEventListener('visibilitychange',visibility);};},[refreshAnalysis,refreshQuotes]);
  useEffect(()=>{refreshMarkets();const t=setInterval(()=>{if(!document.hidden)refreshMarkets();},15000);const visible=()=>{if(!document.hidden)refreshMarkets();};document.addEventListener('visibilitychange',visible);return()=>{clearInterval(t);document.removeEventListener('visibilitychange',visible);};},[refreshMarkets]);
  useEffect(()=>{if(tab==='archive')refreshJournal();},[tab,refreshJournal]);
  const selected=data[asset],f=selected?.forecasts?.find((x:any)=>x.horizon===horizon),valid=f?.p!==null&&f?.p!==undefined&&now<f.validUntil;
  const available=ASSETS.filter(a=>data[a]?.forecasts?.some((x:any)=>x.p!==null&&x.p!==undefined)).length;
  const live=ASSETS.filter(a=>quotes[a]?.quotes?.some((x:any)=>x.price&&(!x.sourceAt||now-x.sourceAt<30000)&&now-x.receivedAt<30000)).length;
  const price=quotes[asset]?.quotes?.find((x:any)=>x.source==='Kraken'&&x.price),nextCut=(Math.floor(now/300000)+1)*300000;
  const markets:any[]=matrix?.rows?.find((r:any)=>r.asset===asset&&r.horizon===horizon)?.markets??[];
  const tabs=[{id:'compare',label:'Comparar mercados',icon:Activity},{id:'daily',label:'Agenda de 24 horas',icon:Clock3},{id:'desk',label:'Mesa de análisis',icon:Layers3},{id:'archive',label:'Archivo y resultados',icon:Database},{id:'method',label:'Modelo y fuentes',icon:BookOpen}];
  const headings:any={compare:['Comparador','Todas las fuentes, a la vista.','Seis monedas y ventanas5/15/60min. Precios y probabilidades con sus reglas y fechas.'],daily:['Agenda diaria','El día, ventana por ventana.','24,96 o288 ventanas: estimaciones emitidas y capturas con su hora original.'],desk:['Observatorio','Observar antes de decidir.','Criptomonedas, probabilidades y contexto para investigación.'],archive:['Archivo','La evidencia queda registrada.','Pronósticos emitidos antes de conocer su resultado, por activo y horizonte.'],method:['Metodología','Un modelo, sin falsas certezas.','Lo que sabemos, lo que estimamos y lo que todavía falta validar.']};
  return <div className="app-shell"><aside className="sidebar"><a href="/" className="brand"><span className="omega-mark">Ω</span><span>MONEY <em>Ω</em><small>OBSERVATORIO</small></span></a><div className="nav-label">ESPACIO DE INVESTIGACIÓN</div><nav>{tabs.map(t=><button key={t.id} title={t.label} aria-label={t.label} onClick={()=>setTab(t.id)} className={'nav-item '+(tab===t.id?'active':'')}><t.icon size={18}/>{t.label}{tab===t.id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-rule"/><div className="nav-label">ENTORNO</div><div className="environment"><i/>PAPER · solo consulta</div><p className="sidebar-copy">Datos públicos.<br/>Decisiones humanas.<br/>Ninguna orden automática.</p><div className="sidebar-bottom"><div className="private-label"><LockKeyhole size={15}/> Espacio privado</div>MONEY Ω / Ω PREDICT<br/>Observatorio v0.2.0</div></aside>
    <div className="main-area"><header className="topbar"><div className="breadcrumb">MONEY Ω <span>/</span> {headings[tab][0]}</div><div className="topbar-right"><span className="clock"><Clock3 size={14}/>{time(now)} <span>CDMX</span></span><span className="read-only"><ShieldCheck size={14}/> Sin ejecución</span></div></header><main className="workspace">
      <div className="page-heading"><div><div className="eyebrow"><i/>INTELIGENCIA DE MERCADOS</div><h1>{headings[tab][1]}</h1><p>{headings[tab][2]}</p></div><button className="button subtle" onClick={()=>{refreshAnalysis();refreshQuotes();refreshMarkets();if(tab==='archive')refreshJournal();}} disabled={busy||marketBusy}><RefreshCw size={15} className={busy||marketBusy?'spin':''}/>{busy||marketBusy?'Consultando…':'Actualizar'}</button></div>
      <div className="warning-banner"><ShieldCheck size={18}/><p><strong>Modo investigación.</strong> Pspot experimental, no calibrada. No es probabilidad de acierto de un contrato ni una instrucción de compra.</p><span className="badge amber">NO HAY EDGE DEMOSTRABLE</span></div>
      {tab==='compare'&&<MarketComparator matrix={matrix} now={now} data={data} quotes={quotes} busy={busy} onSelect={(a:string,h:number)=>{setAsset(a);setHorizon(h);}}/>}
      {tab==='daily'&&<DailyCalendar now={now}/>}
      {tab==='desk'&&<><section className="metrics"><div className="metric"><span>Activos observados <Activity size={15}/></span><strong>{live}<em>/ 6</em></strong><small>Precios REST observados · no tick a tick</small></div><div className="metric"><span>Modelos spot disponibles <BarChart3 size={15}/></span><strong>{available}<em>/ 6</em></strong><small>Disponibilidad no significa precisión validada</small></div><div className="metric"><span>Próximo corte de análisis <Clock3 size={15}/></span><strong>{remaining(nextCut,now)}</strong><small>Cada5min · mientras la página esté abierta</small></div><div className="metric"><span>Ventaja operativa demostrada <ShieldCheck size={15}/></span><strong className="metric-word">Ninguna</strong><small>No se habilita ejecución en V1</small></div></section>
        <div className="section-toolbar"><div className="section-title"><h2>Lista de seguimiento</h2><span>6 activos</span></div><div className="toolbar-controls"><div className="segment" aria-label="Horizonte">{[5,15,60].map(h=><button key={h} className={horizon===h?'selected':''} onClick={()=>setHorizon(h)}>{h===60?'1 hora':h+' min'}</button>)}</div><label className="search"><Search size={15}/><input aria-label="Buscar activo" placeholder="Buscar activo" value={filter} onChange={e=>setFilter(e.target.value)}/></label></div></div>
        <section className="asset-grid">{ASSETS.filter(a=>(a+' '+(NAMES as any)[a]).toLowerCase().includes(filter.toLowerCase())).map(a=>{const d=data[a],fc=d?.forecasts?.find((x:any)=>x.horizon===horizon),ok=fc?.p!==null&&fc?.p!==undefined&&now<fc.validUntil,q=quotes[a]?.quotes?.find((x:any)=>x.source==='Kraken'&&x.price);return <button key={a} className={'asset-card '+(a===asset?'chosen':'')} onClick={()=>setAsset(a)} aria-pressed={a===asset}><div className="asset-card-header"><div className="asset-name"><span className="coin" style={{background:colors[a]+'18',color:colors[a]}}>{symbols[a]}</span><span><strong>{(NAMES as any)[a]}</strong><small>{a} / USD</small></span></div><span className={'badge '+(ok?'muted':'dim')}>{ok?'WATCH':fc?.p?'NO PLAY':'SIN DATOS'}</span></div><div className="asset-price"><strong>{money(q?.price)}</strong><small>{q?(now-q.receivedAt<30000?'Kraken · observado':'Precio desactualizado'):(quotes[a]?'Feed no disponible':'Consultando feed…')}</small></div><Chart points={d?.candles??[]} small/><div className="asset-estimate"><span>Sesgo spot experimental <CircleHelp size={12}/></span>{ok?<strong className={fc.direction==='UP'?'green':fc.direction==='DOWN'?'red':'neutral'}>{fc.direction==='UP'?<ArrowUpRight size={17}/>:fc.direction==='DOWN'?<ArrowDownRight size={17}/>:<ArrowRight size={17}/>} {fc.direction==='UP'?'Arriba':fc.direction==='DOWN'?'Abajo':'Sin sesgo'} {pct(fc.direction==='UP'?fc.p:1-fc.p)}</strong>:<strong className="no-estimate">{d?'Sin estimación vigente':'Calculando…'}</strong>}</div><div className="asset-card-foot"><span>{ok?'No calibrado · excluye empates':fc?.reason??d?.error??'Solo datos reales, no demostración'}</span><ArrowRight size={13}/></div></button>;})}</section>
        <div className="detail-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">PROYECCIÓN SPOT · {horizon} MIN</span><h2>{(NAMES as any)[asset]} <span>{asset} / USD</span></h2></div><span className="badge muted">{selected?.source??'Kraken USD'}</span></div><div className="chart-price"><strong>{money(price?.price)}</strong><span>Recibido {time(price?.receivedAt)} · timestamp de fuente no disponible</span></div><Chart points={selected?.candles??[]}/><div className="chart-axis"><span>{time(selected?.candles?.[0]?.t)}</span><span>Histórico cerrado, no pronóstico</span><span>{time(selected?.candles?.at(-1)?.t)}</span></div><div className="forecast-box"><div className="forecast-main"><span>Mayor probabilidad experimental</span><strong className={valid?(f.direction==='UP'?'green':f.direction==='DOWN'?'red':'neutral'):''}>{valid?(f.direction==='UP'?'ARRIBA':f.direction==='DOWN'?'ABAJO':'SIN SESGO'):'Sin estimación vigente'} {valid&&pct(f.direction==='UP'?f.p:1-f.p)}</strong><small>{valid?'Condicional a movimiento; excluye empates.':f?.reason??selected?.error??'Esperando histórico público verificable.'}</small></div>{valid&&<div className="forecast-time"><Clock3 size={14}/><span>Revisión en {remaining(f.validUntil,now)}<small>Resultado {time(f.target)}</small></span></div>}</div><div className="forecast-stats"><div><span>Precio de referencia</span><strong>{money(f?.reference)}</strong><small>{time(f?.origin)} · cierre Kraken</small></div><div><span>Mediana proyectada</span><strong>{valid?money(f.medianPrice):'—'}</strong><small>No es objetivo de Polymarket</small></div><div><span>Banda de precio P10–P90</span><strong className="small-number">{valid?money(f.priceBand[0])+' – '+money(f.priceBand[1]):'—'}</strong><small>Cobertura predictiva no validada</small></div></div><details className="details"><summary>Modelo, evaluación y argumento contrario <ChevronDown size={14}/></summary><p>30 análogos (mínimo15 no planos); {f?.trainCount??0} ventanas de entrenamiento; {selected?.candleCount??0} velas5m. Muestra corta: no acredita calibración.</p><p>Frecuencia aproximada (Wilson): {pct(f?.interval?.[0])} – {pct(f?.interval?.[1])}; supuestos binomiales no garantizados. Empates: {pct(f?.flatFrequency)}.</p><p>Backtest temporal purgado: {f?.backtest?.n??0} casos; Brier modelo {f?.backtest?.modelBrier?.toFixed(4)??'—'}, baseline0.5 {f?.backtest?.naiveBrier?.toFixed(4)??'—'}, baseline histórico {f?.backtest?.historicalBrier?.toFixed(4)??'—'}. No evalúa contratos ni costes.</p><p><strong>Red team:</strong> {f?.redTeam??'Sin datos no existe tesis verificable.'}</p><p><strong>Invalidación:</strong> {f?.invalidation??'Fuente inaccesible, datos antiguos, gaps o referencia contractual desconocida.'}</p></details></section>
          <section className="panel"><div className="panel-heading"><div><span className="eyebrow">PROBABILIDAD DEL MERCADO</span><h2>Contratos de referencia</h2></div><Radio size={18} className={marketBusy?'spin':'muted-icon'}/></div><p className="market-note">Son mercados distintos. No se trasladan sus porcentajes ni Pspot a la pantalla de Coinbase.</p>{markets.length===0?<div className="market-empty">Consultando contratos públicos…</div>:markets.map((m,i)=>{const expired=m.expiresAt&&now>=m.expiresAt;const ts=[m.up?.sourceAt,m.down?.sourceAt].filter((x:any)=>Number.isFinite(x));const stale=now-m.receivedAt>=30000||(ts.length>0&&now-Math.min(...ts)>=30000);const down=m.down?.mid??(m.down?.bid!==null&&m.down?.ask!==null&&m.down?.bid!==undefined&&m.down?.ask!==undefined?(m.down.bid+m.down.ask)/2:null);return <article key={i+m.venue} className="market-contract"><div className="contract-top"><strong>{m.venue}</strong><span className="badge dim">{expired?'EXPIRADO':stale?'COTIZACIÓN VIEJA':m.status==='OBSERVADO'?'OBSERVADO':'NO DISPONIBLE'}</span></div>{m.status==='OBSERVADO'?<><h3>{m.title}</h3><div className="contract-meta"><span>Referencia <b>{money(m.reference)}</b></span><span>Cierra {time(m.expiresAt)} <b>{remaining(m.expiresAt,now)}</b></span></div><div className="market-probabilities"><div><span>Arriba · midpoint</span><strong className="green">{pct(m.pMarket)}</strong><small>Ask {pct(m.up?.ask)} · Bid {pct(m.up?.bid)}</small></div><div><span>Abajo · midpoint propio</span><strong className="red">{pct(down)}</strong><small>Ask {pct(m.down?.ask)} · Bid {pct(m.down?.bid)}</small></div></div><div className="contract-warning"><CircleHelp size={14}/> Pmodelo del contrato: no disponible. Sin edge neto calculable.</div><details className="details"><summary>Reglas, ID y liquidez <ChevronDown size={13}/></summary><p>ID: {m.id}</p><p>Referencia exacta del rótulo: {m.referenceLabel??'no disponible'}. {m.precisionWarning?'ADVERTENCIA: precisión del rótulo y campo numérico diferente; no usar como equivalentes.':''}</p><p>{m.pMarketKind}</p><p>Recibido {time(m.receivedAt)}. Timestamp libroUP {time(m.up?.sourceAt)}. Metadatos no confirman frescura de cotización.</p><p>Profundidad askUP {m.up?.depthAtAsk??'no verificada'}; mínimo {m.up?.minOrderSize??'no verificado'}. Costes totales no verificados.</p><p>Resolución: {m.resolutionSource}</p><p className="rules-text">{m.rules}</p><p>{m.reason}</p><a href={m.url} target="_blank" rel="noopener noreferrer">Fuente contractual <ExternalLink size={12}/></a></details><div className="signal-label">{expired?'NO PLAY':'DATA INSUFFICIENT'}</div></>:<p className="source-error">{m.error}</p>}</article>;})}<div className="trust-note"><span className="trust-symbol">T</span><div><strong>Trust Wallet</strong><p>Acceso directo no configurado. Integra otros proveedores; no es un modelo independiente.</p></div><span className="badge dim">PENDIENTE</span></div></section></div>
        <div className="bottom-strip"><span><Database size={15}/>{selected?.archive?.status==='GUARDADO'?'Corte respaldado en el archivo del sitio':selected?.archive?.note??'Esperando corte respaldado'}</span><JsonButton label="Exportar este corte" value={async()=>({generatedAt:new Date().toISOString(),executionEnabled:false,analysis:data,quotes,markets,warning:'Pspot no es Pcontrato; no calibrado.'})}/></div>
      </>}
      {tab==='archive'&&<><div className="archive-info"><Database size={22}/><div><h2>Archivo prospectivo · PAPER</h2><p>Se guarda el primer pronóstico por activo, horizonte y referencia. Resultados contra la misma fuente Kraken en consultas posteriores. No hay apuestas ni posiciones.</p><small>Al cerrar la página se detiene la recolección. Drive/GitHub respaldan la entrega y documentación; no cada nuevo corte automáticamente.</small></div></div><section className="panel"><div className="panel-heading"><div><span className="eyebrow">EVALUACIÓN POR COHORTE</span><h2>Acumulamos evidencia, no certeza.</h2></div><JsonButton label="Exportar archivo JSON" value={async()=>{const records:any[]=[];let offset=0,more=true,summary:any[]=[];while(more&&offset<25000){const r=await fetch('/api/history?asset=ALL&limit=500&offset='+offset);if(!r.ok)throw new Error();const j:any=await r.json();records.push(...j.records);summary=j.summary;more=j.hasMore;offset=j.nextOffset;}return {generatedAt:new Date().toISOString(),records,summary,truncated:more,warning:'Máximo25000 por exportación; sin calibración validada.'};}}/></div><div className="table-wrap"><table><thead><tr><th>Activo / horizonte</th><th>Emitidas</th><th>Evaluadas</th><th>Brier prospectivo</th><th>Calibración</th></tr></thead><tbody>{archive?.summary?.length?archive.summary.map((s:any)=><tr key={s.asset+s.horizon+s.source+s.version}><td>{s.asset} / {s.horizon}min<small className="cohort-label">{s.source} · v{s.version}</small></td><td>{s.total}</td><td>{s.evaluated??0}</td><td>{s.brier?.toFixed(4)??'—'}</td><td><span className="badge amber">NO VALIDADA</span></td></tr>):<tr><td colSpan={5} className="empty-table">{archive?.error??'Todavía no hay pronósticos registrados. Se necesita histórico válido primero.'}</td></tr>}</tbody></table></div><p className="table-caption">Brier menor es mejor. Comparar con baselines del mismo evento. Empates excluidos; pronósticos consecutivos15/60m se solapan, no son muestras independientes.</p></section><section className="panel journal-panel"><div className="panel-heading"><h2>Últimas 100 predicciones</h2><span className="badge dim">Sin edición de resultados</span></div><div className="table-wrap"><table><thead><tr><th>Emitida · CDMX</th><th>Activo</th><th>Ventana</th><th>Pspot ↑</th><th>Referencia</th><th>Resultado a las</th><th>Resultado</th></tr></thead><tbody>{archive?.records?.length?archive.records.map((r:any)=><tr key={r.id}><td>{date(r.created)}</td><td>{r.asset}</td><td>{r.horizon}min</td><td>{pct(r.probability)}</td><td>{money(r.reference)}</td><td>{time(r.target)}</td><td><span className={'badge '+(r.outcome==='UP'?'green-badge':r.outcome==='DOWN'?'red-badge':'dim')}>{r.outcome??'PENDIENTE'}</span></td></tr>):<tr><td colSpan={7} className="empty-table">No se inventa un historial de aciertos.</td></tr>}</tbody></table></div></section></>}
      {tab==='method'&&<><div className="method-grid"><section className="panel"><span className="eyebrow">01 / QUÉ ESTIMA</span><h2>Precio spot, no resolución contractual.</h2><p>Compara retornos trailing5/15/60min con30 análogos anteriores de la misma fuente. Psubida está condicionada a que haya movimiento. Bandas P10–P90 son descriptivas, no cobertura validada.</p><p>Solo velas cerradas. Normalización basada en entrenamiento. Labels no solapadas por horizonte y backtest temporal con purga adicional. Mínimo40 ventanas elegibles: umbral técnico, no evidencia de precisión.</p><div className="method-callout">MONEY_SPOT_ANALOG_V1_PAPER<br/><strong>calibrated=false · execution_enabled=false</strong></div></section><section className="panel"><span className="eyebrow">02 / CUÁNDO SE ABSTIENE</span><h2>La máquina también dice “no sé”.</h2><p>Pmodelo contractual permanece vacía sin oráculo, referencia y modelo adecuados. No se calcula EV con Pspot. Un porcentaje alto no prueba rentabilidad: faltan costes, liquidez y validación.</p><p>5/15/60min no tienen la misma referencia. Su cruce no prueba cambio de tendencia. Dos cuentas no diversifican una exposición correlacionada.</p><div className="method-callout">WATCH = observación experimental.<br/><strong>DATA INSUFFICIENT = abstención, no recomendación.</strong></div></section></div><section className="panel sources-panel"><div className="panel-heading"><div><span className="eyebrow">03 / INTEGRACIONES</span><h2>Fuentes con nombre y límites.</h2></div><span className="badge muted">Solo lectura pública</span></div>{sources.map(s=><div className="source-row" key={s[0]}><div><strong>{s[0]}</strong><p>{s[2]}</p></div><span className="badge dim">{s[1]}</span><a href={s[3]} target="_blank" rel="noopener noreferrer" aria-label={'Documentación '+s[0]}><ExternalLink size={15}/></a></div>)}</section><section className="panel continuity-panel"><span className="eyebrow">04 / CONTINUIDAD</span><h2>Un módulo independiente de MONEY Ω.</h2><p>RENOVA_DESK_V0 queda congelado: BTC-USD,EMA12/26,1H,14días,PAPER. No se envían instrucciones a Grok ni cuentas de trading.</p><p>GitHub respalda código y documentación técnica sanitizada. Drive: archivo privado de esta entrega y decisiones conocidas. El sitio: observaciones y pronósticos persistentes al consultar. No existe sincronización automática de todas las conversaciones invisibles de ChatGPT.</p><div className="source-links"><a target="_blank" rel="noopener noreferrer" href="https://github.com/reyfilosofo/renova-agent/blob/main/omega-predict/MASTER_PROTOCOL.md">Protocolo maestro <ExternalLink size={13}/></a><a target="_blank" rel="noopener noreferrer" href="https://github.com/Polymarket/ts-sdk">SDK oficial Polymarket <ExternalLink size={13}/></a><a target="_blank" rel="noopener noreferrer" href="https://github.com/gregyoung14/openmarket">OpenMarket · investigación <ExternalLink size={13}/></a></div></section></>}
      <footer><span>MONEY Ω <b>/</b> OBSERVATORIO</span><p>Informativo. Sin apuestas, órdenes ni garantías.</p><span>America/Mexico_City</span></footer>
    </main></div></div>;
}
