'use client';
import { useState } from 'react';
import { ArrowUpRight,ArrowDownRight,ExternalLink,Download,ChevronDown,Layers3 } from 'lucide-react';
import { NAMES } from '@/lib/market-data.mjs';
import { compareMarkets,freshness } from '@/lib/comparison.mjs';
const pct=(v:any)=>typeof v==='number'&&Number.isFinite(v)?(v*100).toFixed(1)+'%':'—';
const cash=(v:any)=>typeof v==='number'&&Number.isFinite(v)?'$'+new Intl.NumberFormat('es-MX',{maximumFractionDigits:v<10?6:2}).format(v):'—';
const clock=(t:any)=>typeof t==='number'&&Number.isFinite(t)?new Intl.DateTimeFormat('es-MX',{timeZone:'America/Mexico_City',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(t):'—';
const fieldNames:any={quoteUnit:'USD/USDT',startAt:'inicio',endAt:'fin',referenceExact:'referencia exacta',oracleProvider:'oráculo',oracleFeedId:'feed',priceStatistic:'estadístico',operator:'comparador',tiePayout:'empate',rounding:'redondeo',voidPayout:'anulación',payoutCurrency:'moneda de pago',rulesVersion:'versión de reglas'};
function VenueCell({m,now,basis}:{m:any;now:number;basis:string}){
  if(!m||m.status!=='OBSERVADO')return <div className="venue-unavailable"><span className="badge dim">{m?.status??'CONSULTANDO'}</span><small>{m?.error??'Esperando una fuente válida.'}</small></div>;
  const age=freshness(m,now),old=['STALE','EXPIRED','CLOCK_INVALID'].includes(age.grade);
  const value=(side:string)=>{const book=m[side];return basis==='ask'?book?.ask:basis==='bid'?book?.bid:book?.mid??(typeof book?.bid==='number'&&typeof book?.ask==='number'?(book.bid+book.ask)/2:side==='up'?m.pMarket:null);};
  return <div className={'venue-quote '+(old?'quote-old':'')}><div className="quote-duo"><span className="green"><ArrowUpRight size={12}/>{pct(value('up'))}</span><span className="red"><ArrowDownRight size={12}/>{pct(value('down'))}</span></div><small>{basis==='ask'?'Compra · ask bruto':basis==='bid'?'Venta · bid bruto':'Midpoint · indicador de mercado'}</small><div className="quote-costs">↑ {cash(m.up?.ask)} · ↓ {cash(m.down?.ask)} <em>/ unidad, sin costes finales</em></div><span className={'freshness '+(age.grade==='OBSERVED_RECENTLY'?'recent':'')}>{age.label}</span><small>Rec. {clock(m.receivedAt)} · Libro {clock(m.up?.sourceAt)}</small><small>Referencia {cash(m.reference)} {m.spec?.quoteUnit??'sin moneda verificada'}</small></div>;
}
function DownloadMatrix({matrix}:any){return <button className="button subtle" disabled={!matrix} onClick={()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(matrix,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='MONEY_OMEGA_COMPARADOR_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(u);}}><Download size={14}/>Exportar captura</button>;}
export default function MarketComparator({matrix,now,data,quotes,onSelect,busy}:any){
  const [h,setH]=useState(0),[basis,setBasis]=useState('ask'),[detail,setDetail]=useState('BTC:60');
  const rows=matrix?.rows??[],filtered=rows.filter((r:any)=>!h||r.horizon===h),selected=rows.find((r:any)=>r.asset+':'+r.horizon===detail);
  const observed=rows.reduce((n:number,r:any)=>n+r.markets.filter((m:any)=>m.status==='OBSERVADO').length,0);
  return <div className="comparator-page">
    <section className="comparison-intro"><div><span className="eyebrow">SEIS ACTIVOS · TRES VENTANAS · FUENTES SEPARADAS</span><h2>Un reloj común. Cada contrato conserva sus reglas.</h2><p>Verde indica UP; rojo indica DOWN. La cifra mostrada depende del precio elegido. No significa que el modelo valide esa probabilidad ni que un proveedor tenga el porcentaje “original”.</p></div><span className="badge muted">{matrix?'18 ventanas':'CONSULTANDO'}</span></section>
    <section className="metrics comparator-metrics"><div className="metric"><span>Libros / contratos observados</span><strong>{observed}<em>/54</em></strong><small>Disponibilidad y frescura se verifican por separado</small></div><div className="metric"><span>Última captura del servidor</span><strong className="time-number">{clock(matrix?.completedAt)}</strong><small>CDMX · amplitud de consulta {matrix?(matrix.requestSpanMs/1000).toFixed(2)+'s':'—'}</small></div><div className="metric"><span>Predict Mainnet</span><strong className="metric-word">{matrix?.predictConfigured?'Configurado':'Pendiente'}</strong><small>API oficial requiere clave; sin datos inventados</small></div><div className="metric"><span>Comparación económica</span><strong className="metric-word">Por validar</strong><small>Oráculos, referencias, empates y coste final</small></div></section>
    <div className="comparison-toolbar"><div className="segment">{[0,5,15,60].map(v=><button key={v} className={h===v?'selected':''} onClick={()=>setH(v)}>{v===0?'Todos':v===60?'1 hora':v+' min'}</button>)}</div><div className="basis-control"><label htmlFor="quote-basis">Precio mostrado</label><select id="quote-basis" value={basis} onChange={e=>setBasis(e.target.value)}><option value="ask">Ask · coste de compra</option><option value="mid">Midpoint · probabilidad implícita</option><option value="bid">Bid · precio de venta</option></select></div><DownloadMatrix matrix={matrix}/></div>
    <section className="panel matrix-panel"><div className="table-wrap"><table className="matrix-table"><thead><tr><th>Activo · precio spot</th><th>Ventana CDMX</th><th>Polymarket</th><th>Predict.fun<small>Acceso Binance Wallet</small></th><th>Kalshi<small>Referencia Coinbase Predictions</small></th><th>Poly − Predict<small>Midpoint UP · puntos</small></th><th>Modelo spot<small>Horizonte rodante, distinto del contrato</small></th></tr></thead><tbody>{filtered.length?filtered.map((r:any)=>{
      const p=r.markets.find((m:any)=>m.provider==='POLYMARKET'),d=r.markets.find((m:any)=>m.provider==='PREDICT'),k=r.markets.find((m:any)=>m.provider==='KALSHI'),comp=compareMarkets(p,d,now);
      const f=data[r.asset]?.forecasts?.find((v:any)=>v.horizon===r.horizon),valid=f?.p!==null&&f?.p!==undefined&&now<f.validUntil;
      const q=quotes[r.asset]?.quotes?.find((v:any)=>v.source==='Coinbase spot'&&v.price)??quotes[r.asset]?.quotes?.find((v:any)=>v.price);
      return <tr key={r.asset+r.horizon} className={detail===r.asset+':'+r.horizon?'matrix-selected':''}><td><button className="asset-link" onClick={()=>{setDetail(r.asset+':'+r.horizon);onSelect(r.asset,r.horizon);}}>{r.asset}<span>{(NAMES as any)[r.asset]}</span></button><strong className="spot-small">{cash(q?.price)}</strong><small>{q?.source??'Feed no disponible'} · recibido {clock(q?.receivedAt)}</small></td><td><strong>{r.horizon===60?'1 hora':r.horizon+' min'}</strong><small>{clock(r.startAt)} → {clock(r.endAt)}</small><span className="slot-state">{now>=r.endAt?'VENCIDO':now<r.startAt?'FUTURO':'EN CURSO'}</span></td><td><VenueCell m={p} now={now} basis={basis}/></td><td><VenueCell m={d} now={now} basis={basis}/></td><td><VenueCell m={k} now={now} basis={basis}/></td><td><strong className="delta-neutral">{comp.midpointDifferencePp===null?'—':(comp.midpointDifferencePp>0?'+':'')+comp.midpointDifferencePp.toFixed(1)+' pp'}</strong><span className="badge amber">{comp.semanticGrade==='EXACT'?'REGLAS COINCIDENTES':comp.semanticGrade==='DIFFERENT'?'CONTRATOS DISTINTOS':'EQUIVALENCIA NO VERIFICADA'}</span><small>{comp.timingGrade} · no edge</small></td><td>{valid?<><strong className={f.direction==='UP'?'green':f.direction==='DOWN'?'red':'neutral'}>{f.direction==='UP'?'↑':f.direction==='DOWN'?'↓':'↔'} {pct(f.direction==='DOWN'?1-f.p:f.p)}</strong><small>Mediana {cash(f.medianPrice)}</small><small>{clock(f.origin)} → {clock(f.target)}</small><span className="freshness">EXPERIMENTAL · NO CALIBRADO</span></>:<small>{busy?'Consultando modelo…':'Sin estimación vigente'}</small>}</td></tr>;
    }):<tr><td colSpan={7} className="empty-table">{matrix?.error??'Consultando contratos y referencias de los tres plazos. Sin cuotas de demostración.'}</td></tr>}</tbody></table></div><p className="table-caption">Ask es el coste bruto observado de una unidad, sujeto a tamaño disponible y mínimos. UP y DOWN no se fuerzan a sumar100%. La consulta se agrupa cada15s; eso no garantiza cotizaciones simultáneas. Selecciona el activo para inspeccionar su contrato.</p></section>
    {selected&&<section className="panel matrix-detail"><div className="panel-heading"><div><span className="eyebrow">AUDITORÍA DE LA VENTANA</span><h2>{selected.asset} · {selected.horizon} min · {clock(selected.startAt)}–{clock(selected.endAt)}</h2></div><span className="badge muted">Sin ejecución</span></div><div className="venue-detail-grid">{selected.markets.map((m:any)=><article key={m.provider}><h3>{m.venue}</h3>{m.status==='OBSERVADO'?<><p>{m.title}</p><dl><dt>Objetivo contractual</dt><dd>{cash(m.reference)} {m.spec?.quoteUnit??''}</dd><dt>Fuente / estadístico</dt><dd>{m.spec?.oracleProvider??'No verificado'} / {m.spec?.priceStatistic??'No verificado'}</dd><dt>Regla UP / empate</dt><dd>{m.spec?.operator??'No verificado'} / {m.spec?.tiePayout??'No verificado'}</dd><dt>Ask UP / DOWN</dt><dd>{cash(m.up?.ask)} / {cash(m.down?.ask)}</dd><dt>Subtotal venue por unidad*</dt><dd>{cash(m.costUp?.venueSubtotal)} / {cash(m.costDown?.venueSubtotal)}</dd><dt>Liquidez al ask UP</dt><dd>{m.up?.depthAtAsk??'No verificada'}</dd></dl><small>*Indicativo: usa tarifa recibida, sin ruta, gas, conversión, slippage ni comprobar mínimos. Coste final de wallet: no disponible. No cotizar con un libro vencido.</small><details className="details"><summary>Reglas completas e identificador <ChevronDown size={13}/></summary><p>ID {m.id}</p><p>Feed {m.spec?.oracleFeedId??m.resolutionSource??'No verificado'}</p><p>Recibido {clock(m.receivedAt)}; fuente libro {clock(m.up?.sourceAt)}</p><p className="rules-text">{m.rules}</p><a href={m.url} target="_blank" rel="noopener noreferrer">Contrato original <ExternalLink size={12}/></a></details></>:<p>{m.error}</p>}</article>)}</div><p className="table-caption">Campos que impiden equivalencia: {selected.comparison?.mismatches?.map((k:string)=>fieldNames[k]??k).join(', ')||selected.comparison?.missing?.map((k:string)=>fieldNames[k]??k).join(', ')||'Por verificar'}. El modelo spot no usa la referencia de estos contratos.</p></section>}
    <section className="panel wallet-map"><div className="panel-heading"><div><span className="eyebrow">VÍAS DE ACCESO Y COSTES</span><h2>La wallet y el proveedor son capas distintas.</h2></div><Layers3 size={18}/></div><div className="table-wrap"><table><thead><tr><th>Aplicación</th><th>Proveedor</th><th>Acceso verificado</th><th>Coste final</th></tr></thead><tbody>{matrix?.accessPaths?.map((p:any)=><tr key={p.name}><td>{p.name}</td><td>{p.providers.join(' / ')}</td><td>{p.state}</td><td>{p.costs}</td></tr>)}</tbody></table></div><p className="table-caption">No se inventan columnas con porcentajes de Trust/MetaMask/Coinbase Wallet: sin un contrato y una cotización directa de la ruta, compartir proveedor no demuestra el mismo coste final ni el mismo retraso.</p></section>
  </div>;
}
